! fplot_glyphs_data — DejaVu Sans outlines, generated by
! tools/gen_glyphs.py. Do not edit.
!
! One base85 string holding the four faces as the font itself stores
! them: quadratic contours in integer font units, deltas coded by
! magnitude class, outlines that repeat between faces stored once.
! fplot_glyphs unpacks it on first use; the format is described
! there and in the generator.

module fplot_glyphs_data
    use fplot_style, only: dp
    implicit none
    public

    real(dp), parameter :: EM = 2048.0_dp
    real(dp), parameter :: ASCENT = 1901.0_dp
    real(dp), parameter :: DESCENT = -483.0_dp
    real(dp), parameter :: XHEIGHT = 1120.0_dp

    integer, parameter :: NCH = 281
    integer, parameter :: NFACE = 4
    integer, parameter :: NSLOT = 1124
    integer, parameter :: NOUT = 499
    integer, parameter :: NCONT = 720
    integer, parameter :: NPT = 11343

    ! The code point ranges the table covers, and where each one
    ! starts in the per-face table.
    integer, parameter :: NBLK = 2
    integer, parameter :: BLK_FIRST(NBLK) = [32, 913]
    integer, parameter :: BLK_LAST(NBLK) = [255, 969]
    integer, parameter :: BLK_OFF(NBLK) = [1, 225]

    character(len=*), parameter :: ALPHABET = &
        "#$%()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz"

    character(len=*), parameter :: BLOB = &
"#?[C2=n+q>0TTgDhHt*(??`J?6)=>@Tde)TJ3p_^jQ>lCi7/q1jQ>lBPeKs>lfgur1eSi.,f#deX8ge/5:sN6$$-cmW1^TNt^gq6ZsxhEf^N><j/8vnp-wI1F:AD$,7zk&
&Y1@j6B;<DW/Q9M^AV>odY.?x)nF1]*JUFM@zFcw5)RGFRkFFK+TgQZx*$.=09+p3NC;U15HV3<05SuP:K^S*IAaA?(/q:]GZrU(>0(%:D[$_?7%=z@[IAFjq%oJ-T-VS7&
&Ra7UhDv*V*^-rPwQROl4kQ(A*ciR$e>h?5k*fF>Xl:<D5uj8D1llShq9B00(91?(;2`;;xl^w,iG]lZv^uZ>HzS/`:D,H*:Xr,Q?J5RlREA<C%=NdDHaDLxDqW0>.u1%W&
&O]%8%+Sb#>L7%EyTbFX`Bp4djY*gbY-`IWvUdl3`Wlhp_t1a1pq+9E;XLjY:TuSnCP6l.G,9/?e#gi#0S%`rNP[Ah,hRngG@.LaiyB><g@;NFB%.^h5e]S=Y$OQRz(-As&
&?>dQFa.DjP0e1k;Yz<h0K,hS+PV0f@wnx@2lS(v8Fl1Q8ETKz)SH`@gLehA2qRX)k,Z9-Y=2CDQYG:Gaj9Ve3>qVwJ(qFc]xWnd6%N^?^ur7,n#3yDB]c<l0LA;%<v;Tu&
&Bf<TZHfWyKHH)7h`3?,F?(ST3p:Iyzlf$7*-nfUyACY>Rb_wrtvcoBA4u=6[94IM[+7[S?_[Oy>0EQiuU4$HCC=8eoYLB[#%g#A>AxFqqEAB,#ssBK^E?`=VY5lvqn2#A&
&9+rgu>tI@.y#DGDj-poQRM^S^fl*38vMiNV79s<(??#=$RUHt`NhH+.r(/ReIU?bhC?O^`Cn(YkSZN3eDVP28u?oDD`(94Z7CAPUL0De`c90.cLG41Q%;5#-KC6Va`1w,&
&h=h)K(;]NjN2+=bQu%h`S0/q2z-WVD<UuPgaOVEX-.AZnJ4*jvc1T7I<_aBL.j38_H5NJj1w-62;>-R=ox%A-1VX0=>)XXuqGgS;xW>v`V_>Q=+]Q*7f%V#A`Loa0)eQt&
&=hYlffn8?62P[(+@;#hxLpuU>0xD$nZxo1#QVbB:;g?fly2MElp#s4/kYAs=n=5eQ%,v%$sx=:1P%xi-GwAoHDroC]Z3RBTr,=MytO4GEsqqVtHlCj@;()Q,<a2-*V)9m&
&3kYdE8=>ov,(@DMI=AtnwWhiS`S7@)lsXhA)$9t(sdVIs1M6c=WG6pv0k29T_tBR+<)]C@OVnL%;*7FAw<2FSlH?+(4u`k4ZJ[pjvfKt1i3psNw#7,=fTSv,E+<9+7rA(&
&P12@$6zD=FVrp?_7r0>Y+K]$ojMKh@ph[r)$ZfM>?W;br2^C.YGf$AzL_VcMJc@t7,)fXPvj<j,IeZOb4sJsL;GE#ynGUe*-E,BbVJ6,x$^mtpCukkHFwgDCNe(_gE?G8&
&lS;T^Y$/675MSv8G0Z+q=u[8ei?8/pVP?hN7MM2T^Xgl(V9tvLeEj?(j5Uo#sO.6e6f@`6[hv2*/$v]YrXT1-=nLwxp:TvlGd]SiC$*61navv?u@esG4]wLrx5i-ojox^&
&mB3l1kv:wq-tg_9,OH+vkM,GDojZu2poN9?Q*Y+5lt^50U[nF>MYNjXyka^=e/9J2`ym9-N)GN;;ii^R]o.$k?1/5p1B+9bLALF5pt$R:U/9Jt;a.[gwKn%z?_G`vWA2*&
&Q;pBsW?8UO]t.OR)k#fVEu/*UE:*1fr;O;G5*Np`OsB%FZa>s1qJu9]ZiAt%m]F_HIKf2k-U`<TLw+ek]onR5%z6fjUyC%kvZDV=[/UEZ4Mb(U$NEV6DOr1S)>IgX+HL3&
&vdSpF04K(]hHKG6d$g.QyCPLWt:F/4J4ln5gtD(.-YirWYwat:z]DVM;mitI@ynoi4j]bbN@6n.5DYbk$T$G)$^]62c9/lIA6?RC:MfFVgx=,4ZudYDQ:$5C=2uOTP.po&
&YAJ[iXz6H%wiMYU_KXWJNM5YVY>iqdZ,$Tw+([LG*>G9AXg5i/J_idu=u=>=B]d3Yl*C>stCiwJ2,tjlPkG;#Wvs.^[cNsb%0%%*a$3eX3OumR3q*1s@?4*c4Hx=6je6g&
&VQ$X(ZTadcngIV.mpBU+>/,.n%<kvIOYlheUkk(1;:x[5f,fmow;Ar7l>tbGk/*+ivL@,B?<B^U/(*Jaj+Z/*UVJ#+>dAZ.tdD`PbY((sJU(dYEU*4evj7?VG?paMKKui&
&]RRGqo-Rgnz/dz?+9W;S,.=n6+VpTzeZhExdpM6_,d%K)9KO<UOD,QH5*OpR$rhfCJ]d#SJi<AgwgCG]I)9h59Jj:xjJ?WsO2b5o]3jFSXsE3<@S5?Gj_]Q6,<c67K%_@&
&_a0^Vxm$U>q?g.,@_-Fk)o=n+lKW-*:arjXW?HZuu.`muV)8X5WXm0DsqFe^pjF;F*(pWM%Z((BKBwF0*mgA,=1gg%_qpeN`qg^:):G7^4IaBai;<M#y*d2Sc:U3Q^GV+&
&]oeRE+qIfNy`qkA^Amy>rysjbM+(c>s:kjV9P%oK$qMdV7j(_@JqOcZXJxi=>b,M1W>LNEsG3<ZEYW[h`qz`e7Q,_K$aF/TY?x;>KmPi:2`Ngwq5IMp^5>z]Vy,jfhko`&
&JbQB3U(Z(t?xt:0kj2HRAzKzkMd[Ebif>--kXP<AkJMwX@;mbb(1?m]SbK0K@jv:cW<e.a2mKLz7_lHNsaYk<GhM2]r)->0lTU49v.v.?j2%>On*>ck[c=VYYPfKXOxxv&
&tpY]RzEVYN8A/1s3g^yMH-gC:Q2mU-lTdAyN6cVce)O(P^=gP#T$BL;BT`wUvVGRAu(7K7[G-eI@a=LL?EGE7:Pl[qbK>E3c1q3XB-R(AM6/UHSlc8/c%yFR/TUSk+vnd&
&QH26QRDopfF4qRV@@Kh/HJ6S0hz@`06^2t.xT$fJ7I]B.#*P>KX0>R@PG*3Y^+StFZmkwLi;1)6z]1G0:L+3z:8V[iDBJ3s%KXI/rMIRb^n$cPsMpwloNcS`]>?F:@ZO/&
&fGzSh[L#/oH6h2D6^Fv2?gx<:OY(66R*0<Qw@`hGXr6eH,He,=qKo+z32TTk,/uFHi+8(30aM*;3qWhxD>o8uh5dhT8cchK$pMek1Ek+p%(4abHLR?DXOB*hHMXKoh9Gp&
&]N@B`X*hcaj5(mEIUx,Q;FP2g6_1+O.[87VUQ;+GJn71eCZBiTp<U=j9Ce.<pBWQY#d6[@Qmbif),@GJOLd:f29sE%o97$):EPej#H-zR/ug(mSQ/HAjk=<qBTDVC>9b^&
&oCN/;fu(,okh+%%A+az`B=jDlgp,sk95qBuj,aXNLN>:P@qa+)s$#Mf6P64/h.^c+;r`.2p1?CtVeDo3HOX<7:vrObsOMCD;<Pt?Q9TQ00`NZgQW`_;G+;)Iv-W[;#`K@&
&U0h`G$ai7J-[g8XwYxY6EajMtaLZ^mOKH]_or_EUdbBqy<P^A@8+9iJu`jlkJ1Y`<>Z#tj8KeQTLS[Obom,ur)C(/(;C(;F$c=@yb-up^1Ihn#8#m$-z=W6C^;EA:pdEN&
&dok,,?Pu2M)3)5ekYEUYDX$rKsA,^M,]8D-5Kj:<3tw)74Q1h^3IT1IxEPP[YD%H-Z>#c:/bC8A-9J3c#MdSF[0@*5>5h,ts=(CQhjS)QqY0Wml>7xO,[jMS*o>oR%@LW&
&1`F^kP,u<?dm<1YRcS:]F?s6/>i`nq,#vdw93<BHoEagfCIi_Rz,3APO7lY<I_fIl-2=SWoz;Ztd?]Q)rCrVPFi-?,ywb-?TxPfjj.@1YR2=;;#CdogC,LnO]wD:vW$-/&
&JlG<g:i-]?Dh<>jM<ITJ,qfl#mjcKABMn^hH8ps(B_-cZxxb:soa*-f7dQkZHgrn>gl[r;.:ccSe@4EQwik*nlfe$>s]St2=*6$)RvK4;FTt@wGe%Ci:phd,HYqbZk<TD&
&)^^OP]9_T_g[iFO07fC2r`(Q^)@7ej@MFZvCrMbNDcwMCXfZK.;/,7V$]Y`X/]`YnHb)zeTh#@)$O7gHeKkwl.Q=suhwhEw^S0iDIa0>n,JTXE0V`JT,XB-BkuOo[RcQ/&
&RVm.5s<i9yDMS[co(3iDy/%<xk[Ibc1dbw1?[bg<MZm)(0q3r4w<:/=SY[pt>Q-qBT0*-id0gnS3Ey_xI5%99HO*Q<h(0_aRTK,If0KWNb4Y@.($eTm#I;P5Uwo<)HQ<u&
&jUSK9%3V<3ZWcqJGr07z1sQ[DPXL:qqXjnL`q4DS0yLgSXEi6LaZB^1Md:EoawOd@#49:[][SEyc[1L_X3n8dC3do`DT*t-^.0k_CiSL0%LLaxw;eom86csR38lK]cv2?&
&W=MEyGqzW5qMY+y3R@,+y];(2,4RbMHl)[cTE^a#+g/X1sfT8/xG_qjKE$Wn/LZ4Mw<%_oE%tFi9NB%ZmE-,h3+NuZeVSrZLI(0%y3j@$eXC7^DKcIID;b2[FZ=*q]5TI&
&GCkSZb7Bp*SaN?2)#ozPtN6s;ZjHlVWm_PJ?5qK@<$,3ANVQ;-5dei8N?85pSyZ=aAKy,/eva>D.=<=7l%-W2F`Nz:Vq(-l26nEZeHm/;sdTm%%vOa`%hTf>nnFd-2O7%&
&?HA9j6=pG5Z*Q8Ug;+%tdc_gcPr4%59q]jTU8v*=YeS8ueH]6_XYl#I4)19w8q:m[ukv*RnH#qruKEEF0nS?_Pts#X4^4l-2#[[Pw1qbL$[gVq9AOHzn[ZS]efOKgR-,]&
&?X?9$MT`L[RqW4:I<pea@+:Hr<lD:*<,G*)[5lcq1?MdNTOJlH1;X,IE_>Xo)]vk>cnnDdJtZx(g8C.ajW2b898m/Iwlx;=4qj)(bbm0+v:w>:PVBY[-hJjs11z*@k1GB&
&O,Q$Q:,8x:e.BKXj-a2dkkWz;<=8=ZX9=F<yyX)5[L4G.qzOJ=-q-*K0f$BXCPpM8=`WX-FOenmA*jeU49,yv5cvwYF1h9;?7a]V@l]lOfGJ%QP]BED8E<Ra_sQ4S8vbV&
&0uz*n;IQP+KjF:3*6x`e(`(a<#^RrB<<l0wVbYE`82mE)KVGp]6A/Wvgsl>LDX^T.)XI#_6Q?/o%mp$Zgn)ObVvKL/,Ko6ZB;T@fy(AlNIh[@il1[_p8ZT(>VAd;ejv5<&
&5#f]CO/6udw?GJY0Tx/((+/=2/zr>S-uyX(#Pvy@1WPj@4H)]J6F47.(_]]QwLR:sA:;UHd>k;LiyXEljLmh*]:I;iDxD@JC9zrqFxr/#2sNZ4:k3v#a4.T8[f_t0ALX/&
&LLGF_;ZPo]Y^qf*?aw?T$i+pmdADvV=0o<jOZc8s_zK6b;x[eZe75z<`UG5s2F0O%7Y)+$lQJmI5syTLA@E_FGszCdosvC,sKVoClaHPkt0[^$2j,dRQ28ToY%S@%E4IU&
&BVqBdjmy(jW%T;l[*tJ7$d)r6L,ijU%#=PpOe8)ECLufqVAn>Df++1KHnAD:kO/ATJ#-<oq,@9$m5@5d)#NHL*]lF[*XpDSU.$c#JakqfuabBxx45HXgM69Gc`:4efi>E&
&18;E@rG;Dp=H9dR0;NF3s;UH_gR@x#1s*j_YZi0>0p[HNN.j;zO0GY+E9Gwd9CPlZ?ekdUije1l*_or_/QPqRNV^qh9/<MVaFe4Q$kJ0Djz;6]C0R^@DtaV#@cRgy?52w&
&xG4aUreLHJ7Is/.1*CIss,JrXWdC%^vpf6r:]6bDO]4bsGbQAoWkr41IW6MV)Ku<Aay[Xg59mB%)amTL6dMh+j,Ir.u<P[ZrmyjUjqIUXGIzo;f>y%C]?FM>5@3G-Gl5#&
&n,n;.e<q66(:l/a21<BTd*s6<n2:#XDEKtYl)xg>8l051@>yg-]h$BK.gx9WT*Az,VG8g/OW71imig)Lc)byYWl3VTbYx3?j]K3sk64e5x.7GAU5k^Dse_)pEvlxMI^>(&
&%N%x797A/aTMIXThHNcMT2/_(IeOHYpBeH20zcvB+lH/y@F%C,%8L]]QTpZ#2]glSmj8ieQ(sL_nb+V2W?2qE7P6G2Q8l)c;%TgqTD]jzocctqN9$DN(yg#[SwVg$w6Z7&
&_v@2Bzl-/1v%y-Vg]7z^wSV,L_;3K)@8_xo+7cZ(0O2,m@m46`jfvtD(kYYZQ.u],we*)II%1Azu/eGx[RK,xC`;)B9;[b98=<P;vv[DbZ>s1x>>Y?^z$?/5mFj;I[+(S&
&cFFDhhbb@qfdN+ebGK6X$@L$?lX=,JRjQJ0H0DVf=D1qwc.SYzZqk;uv;RC_Hg57of5<MEf:SGL<^bWj03Nu.*a+[HB:?3i:JCq9]=eK,1/sV2eN#9qws(r%oPhy_CU?7&
&]))l6kT84+AxYG=eJGp?,f3;0qh>LsCgCQ0zaC4_$=#<E/?O<UCsB7fZAajf`48-aLSbwwAi-+;D99_T5>i;mpdUO0c2xlkmaj-INr?4wB<V7l@?j5M#,>Fk.-LVyRsMb&
&Z-:R`HaY>Ozj/1B=TS%?*we%j:x:?+h5Qv4`qI3Z)[D.D^Ku?WLXuPN+7dH`BDba`ctv$<TWfSigXRNG@wx._;MeCWjuyMq_p+a<YIn`L5R-MOWjm$(wHWQ.wCv9T(EqO&
&:m7lI;k#a>gr$nQZALY%fxj%P:wW/QWHIb*T^J5d2I)wlg^b_<TxC4o%Yb+9;^QGofB_W1O,pr`pXEPB^dowzDpN],@EG9nUFdXC2m;9B$#.E7$K<,;cV>dsSGym<3ja6&
&]h3=uj#,h?zAhxm$?##OIck@QuQ@Hn</X%<oq=ro?)67L1IS:SEgpxgS0<nh#c5ay%+-KC<+.rXxHdM9yR>FEHQV.,e0KTzzPtaT7kQpoNX@J/R_wC^ZsIqKI6F]eb@jV&
&aK*pMERZ%7THqtgbQPnzQTEawId/0fpc/ddC1^O-R5(o1c(>x1RS4dbUcEn2/fu9Lqc7blC2:C8af_S$,OZqg9k04SH9)%s28(/jyl*hp4pq3r4w<:/=SY[pt>Q-arI/y&
&MAB=%g#]5x)SQD%Y,+YmVR#*jSOQ]GpApuNW2(X6F+=<vP3WEIfGIX<Qc(bh?,+/ZltBTY;d%>$kMAsVx$CB1tATQ-A=gZ7XYcZQQZC;F.t]nD+)T:xBJU:K$^4=POjXr&
&>5/RVfi$KNs*YE/7SoH0*ek;hA3i;*bl.9x8^YgA;1sCs@_QXGWN@GlmjbtVcv6jF:qrE+J)jSLV(/NIr#Wag=p-uJ8tWbLXXp^LNFEqVn+5^gh95H1cm):75sHL_nf@Y&
&4N(^23d3A+s[J[C4W/b`Nh+,i9$P$pK%Pb1Xeh-MsbFYI=UH+a8Z,Yj(blnoKYQkp9;nsU)rr8m.Oye=I5F/MnsF;vB#nUKse%vV#9^RL5=aLS8pwz,REoJK:G+Ni,g#1&
&-TVsa8IAzJJ3r]CoaCyOL0-0hg%O)=;Rig]=[1E*-^k;G=Ne/M<c9W;YsL_CRuUqI%Dnv+6wzw-qM_z9Ss@%^hm(3hCjHp4jm.3L;JYG3TSRjN[D.^VoBtKQ<-Vbn]9Pl&
&<r8EcB)[1c1I>uE%Kh>JG(k/R#f.>GytfGY:IWSlYj+aB9zXu;,TH+XI5?p7)yqGrVGE9axc<kWS=Z9j]fD%FTrO*Q^,2i5ii1XNSZ(VkOBARqQ5eb5ER/RBS]i:u*GsQ&
&=*dM5S@-+K2]/*:Mt64stcb=MSM_Mn.SFY-]i4h/R#l4h`[_p%k@S;*wBX[(O6bJ@dsHqwU8pkqIPZWQBw4kx./Ys`XC0:wW/QWHIb,T[d*S2I)wm;<zn>=PtoHk2n^(-&
&%iZqSZ@0V,7>-3%ed@8;.v16oFSjQPuzgBVR2#<.VzQK(.CehKua#eXYe,wdcVHRl61e6_k)(6l*Yl2r*%H>:7tB*o*?zrV>=gQWKu.eK=:ddOu=a<No_$T,*ya/:Kwgs&
&a#F=-<;st=uwGl;2_Y=S-DXa(/Pu4pZfSvAfBoq*EP@=XY/1LQ=G3[3Rog/qR/p[1/x.;L19>ds*p*1B@:t%)[$;3<I;zm5DjP`)A^haQ6d^sJnGk=UBHPPlkGpZWCfd@&
&;6HH;[BkcV%EtaQ7Ut$a?1lU?Ml368lF(q8e-j;S;`Y#^rX+?wnPs7NAnFZs$7VXK.7Sn.nSKKMH.gmV@JA.^mH<kBd+W0jvk3Od7e<;%>MD,tY;<_LWZT(w=V^U`XO(2&
&q6;GQyF_=(b0M5sh3Wx-h7qZmTO_)7usv#]0P`y4mqP:^VV-?3IW+)mnU;vw/J$TXP2[alP,pg;Xzic+Sc@/=T@WU@.,Y],:s8XZ,Ai7fmOhr@6k8DGU:)[ybABM(x@]N&
&s(Zb1Ti0%;=58W-zwB.A.Qncth$KGc7FxG7>p6VRu8w-Zs6ZwpI@qSAY6tp#1+,LAVFci>oRi<3S/A5mtPa@3._F3Tu2dXcwC;.j]d,)]zJM_Zb#L=5jA?7iFire6.^gG&
&y2heabfq;m<$Q1b<DMDY/3LD8aZ1auvTo`?(h4[S92kfKv;J/l24.oMUeoH2;d%Ut4<YkVY+GZ,E%mnmZ^O4r4T4n%:3E:(,8C3>zn$32]$_r4-qR.%u?Q>/szsP$v^5l&
&;ZxxsFWTaU4t?3->>RTY#_;O,gY0d:8,1X,ai%JGQtb8#BEMOaow6m-44xmCh+Q]CUBSg$3$pK.8C9fq-U,Q1/fKuxWXB5/G4S:F$rJNu@VJX2n_$LPe`8^J8U1?L%as`&
&P4Y[P1s>@V)f8tOkg6GwT,xE6oo]y<[MF1S[YS;yPpunE$Ws+nv2-FS`%KBS^;;BS*H5^?OW5=DJ4l-Jog./]m5*TO84XGb$r0e2y?1L+*(D^#oe)nS0js*AsE9V5vZ7H&
&,FXO4KLY5Kl7.h?RGVTCIiQ/T0hJb5d9_>z,3b.,xjT]<oV*o,I#^ak8Wd0GXB<oa%R?zS^WoBWSfntD)1)CPl:N:_[*O:7fV2rP]P?D3#,<_n;YXx_2mt5[OG=BICF,<&
&XOS<m91q->_lk2ddrJ]BQtJnL3o:Q[Yji]B%[OIKPmN@A-a)VXm#zi?kQb(mT0]^P%y7(k3/)5#nYWf(I).4kBb4H2oUPHk+YQT=f83V@w4/WLTeuWI0zsd:tv3$pMwL:&
&1fYVsI?xeUND>,hOlvh(<B,-@i08jTmd_vnk1o6X>U6T0yGA5@/)9E>aMK[^y>`cr(d#4^,b0H6RwmE(DtIfbB:m*[(d)@aZ*zNGB+:QnEk#JXXlmc>2)3q205c92/h?w&
&TasjXs?wpCO2$gH%yY%N-9Oe5]/pah42O9ADeW+^hDYhW2:D#v+>S<cGrw:J8q*$l12qtrCy.$U`<][MQaDP`I71x6<qE?$AkX^hI,ppG2W5MOOk6n1Z-+DX?(+0yfT+1&
&R34b-wLT/B.sR?%Sfyzj_#TqO/csgG4=G1(*(>RGseZ*@SDG7c1K.rDPk3Fo1k+U@d`fcMvtwcs4q?lREPXUs,^8$hVCH>ySAREiMc=4cPPk8Llf20<0U,lHkQAeyq,7V&
&dJ424>ElLl-o0:>0#Yxuf2Nw#=H*w%7]g8x.w-A.Uo*pRc2(T:1iYsjjU%w$vE5iUc)T%1$AGKiR6.tk`V,?t.8(n=gyk9vAb+68@+%>RL;(hc/LqBwfE%HyvfviRM5Oq&
&WbHj(Xq<n94o8i8XUN-/<>j;Ml1,G#k%%ZhmI/(p6KN[TZcQ8T,rf3_/F*32%ITTBrpSbY;neOCvN%*lH,iX;_c5;TiK#PT:](4rfWz+nfGK0$xcLGvVb:6jq+0JK?8^?&
&R(QVcqX8DqPMvSR-HOcR[f%D<LQDN52_I^5H21_E/Y[ZF#@cU%nh]P,u9/pclMzMO^3JXR5*fSg[1q/FRi@Jndz.iFO3rX[#f=,Wm%j/K/9K<2%)b]kGqm91vX8S:)XF.&
&i%A09S]:`o#xlEQ9zDw3a:x-GU8+k1@Q(VWD,SdyQ3t`>B$%90mi*2=fZIBh)ZsZ((ey)p8-S0qduqKKQRf.sS@-^?E*t?KSY9o9`ioTK]9oMWmtLDmhbF%1_NOA`Wo<[&
&,.Mk5sW[F`s[l%l3Jh.uGFXoZT/uASHYpxY];Z2kB[<d@A(vOla2mR)rn.?XPg*lFaXti6Mi#Bnv4xU1B-F6Gollja)+K(gB7.+RQi=v.r=%tQAP*m`lu8lK0<pDjv*[n&
&;npwO1r2al/n;L24:K)p_3HDMfGrT0+^GP<P6%#ll-TzuPE(Ea[E-aCiU=o5O=R,8f:WM(M1]9-<A<(jvQ>q>ThI;@z4hW`#A-/lc]`$T</>jo[JiV<mdFk?2bs7;RM59&
&MbpP;Zto1L[]13lD,?H%_]Kv@7ScT`<xt:s60#>N,0)@>Z6=$/ZsE@V3dt,:LsqT>.Z*[k.c)2)I/a/0$6>JP.cm*.y$tZ=_0cf(mZ+7xD_LpewMzgRZV=Q+,F:Ig*z6f&
&J_i6-Jshd6,dFOmZw=.VOZ2g<NoznWoP`Ndc5+4SS6.7D0xZ/PwfEbRrr9iq6$2yBu4E5(<0[I7`P%ZV-@:7*P,3x>4v?#;@JL%_rk1I_TPw)B7_iNJ%._rULIt:^e^U4&
&5JUpU^@mc-)ZfVlve%u5hu<SU*ok/aLO.)..QW0?*#Ry7n<0SP:P>:LFhG[<[[h.k7T*nv?K+[Yusnf:12)_PT%LgV[ZLhyp3yhksbs6RKf/1=Gr<%Q74bCQ5rQ2r/M)k&
&FT#wL8JcB4lYlFl0Y?#*:YlFMgj*TnE8r6*d*grvTI._(QiSm+?Z2G$cBO.5Q*5+_#_QelQg)]].IYEF;a<tPM9Zd,-fq*lVJBNMvMKDO6TdoRW9g4K7g87h]CuwHdYSg&
&;FkJc1sqneh*JHnPy7wuZ5.=xx<>7E[#0>ljv]fv2Q768vYi:@xq6K1M)#hWl^-)bCQsbs5G;.z;:`^W2>7rV)#k_VdjnPQGmV(ua;$MhzI[s;sG_5Y]:09@JK`L#k^tf&
&Sq>LeKBSa$qhE7sKdgRIBN5L1OJ[TwQ2xE?`U5qJ/7I96_C^#;tS]jIv-=Lgbb(x3mGq-?Cx0ScEQ?$78^1ZDsMK#.Jo`9sZ_]d5WH@dfZdu,5GmK`;/k6c@UBF2q>GlW&
&8d=K]OxI>:L)O=Jc;8h.AC<-E%><L4^b^34E33nkIsh;4=]a#>rdGQ3T2+Z(1q^wn[tya8rR#RBY)H^dL/MWE]UbD_a@4*2cNpWY)cJT^DU`E3UHd^=h[i63-h0VKoG18&
&c1F%z38$wcQ#K>Vd=gPb+cP5VstBE1FiH]f0tJR_TrnwX1w/M-^W-%[pvJTK?-=$0^ep8$r_:FZLh*[]rNtPm+wYIF]edp6Ei(#fE(UK,Ea$`5KBBalj++Vq;-FLFfJ)Y&
&efu((wM;Z2PU>BV/Kj<fA<Q>VB:<l;a3BOfX[5qId[.5,g#ip<f?+If`0CWI5vnrz`6z.OJFi5Z?o[L_,.%%UPR(bjCJ3skL0uQk$W:9Mi>/Zrq/^.(1]+jCQtMdX;8jg&
&8Z+=`g`2Gb%iQ;?bLTx.X*Y?bR]Le$sa?zXS;B:_zCdNetA1X6FX?@Pql?I,2k[s2nY>,OEhn>]:d9XGmj(0Tv7P=PJ*rK1,[)MJTrm>tM]mwE+AN]_I(O`sCLG@qmT<t&
&yOsixUNwGqr2mn=I-j`WXFnM[aoj60Y*6[ah1]DJ@06v9;#+<_0RlF+75WW8C-X)j?hU%yZi#0bu]EHcJ)4PtdY,7h0NJiB=popkEgu=u3<,Qw1m;Yy8gs8p0hF^H#K]k&
&hz7K0+,OLQ*a2?;3hHbjX?vbF,6=KZ:119h3YmwF]O8@$]Q,YcaNak6@I>G;`?pBh%H=i,-zSvMP5Fv4^I,[)_V4T:rWJd0_;l9UJ-g@ZxctdZFK`h_hAr.2v0atY94^d&
&)pagl3QXHB+gMr(RN[qWKmxrmoYnm]D1HwCXQp=UZkeGVu*O3y4Z$G:XITCY[^v(uY74JIL9$ku[=;L(SNMa=0LXF8nFnjW1ptO1Oc-)TQ96brjjA3nPXMj+2/Zk=KZxK&
&iTeGI?:?.HOi(=?FC*C[y<tmS>$EkeyT9t0pT%8LX@ing02@NUv6gKT:@7$-^ii[5x]rZo@hOYm6=j<3u>9*Nn0-Gu9?XFfASRwcx[D>.PN[vXb@i;ABEwcYMh-M,.<vc&
&$FNAOYNfxNn*[Y[5_vNtRb@?t8U5N+;0<Kb:nIFZc%4fHJyhZV(,JWm0pbWEa2CTTv*?R(9E2Y*F$Pf^QjjRR9L0sf`,X#E+WdCZuxv31t;6>3+^`Sfh.6u9dF/mb[Gx7&
&mnHc]hSKctZ,B(LTg[3bQ8.`AWrMr`5c77AR58v8tjoP(FVCNgHu_:#=rA$i5lbSy=RmXQB3P)FC>hJYkb3dw-GO#lLwR5>%?qo+b,u/_0+JkDZk5Q?>`^AE;5vLcXU*1&
&a[eo9vKiw:t#ft[mj4DAqguKV4<wQgJhU#KwVTndrsChe?_oZeg>oG_C2QKD9T3Y?Fbp>_Nb1s0om@A]Hpz/D9v[`3Ai0.UvFr$AKDLnI9>)97,t%4kARvS]@dw#n4/=z&
&.,6n4#;pV1/+I0`AUnZedNQFDQe4<ni60*7TJBjIR<),Y=?Y7F1#=E2]QX+0jqe283y<caQ.W`KAg*5qTbq-J60n,S5r#7_?zLB>[(cVE2v0a3Q46Zt[Y3$hAqj#w3wbi&
&5e.zJVvT/cqY6M@_d_S+J?>(W=@QY)s1DnFusEl^@[kuJKF=LWjGdE0I3v7lyoTa.H)hd%.+Hk(O-9?%Wfms7eOQl06Pl-/.a3;OU8,w(M^_qL(i:/K:9rixJ@LI0NOch&
&(6%Yn>%@r@L(YenX;mcK#q7mlC+<4]3;;fr(gNSOu/Z_`WPi%ldg=G$2$$_?_=.ABBpY0uSgWjRZS58dov[,x2-pfJnf.I<%kT>6z),sUIV8$@;]=^ylP0,PD5nn$%S.o&
&5zZ1<DO_sRVCZIe?UTVAx^$;4$dFeHJnejAjq>_0_Y<5WXUk<q28;EM?G_WjJv+0GGufeE>`%pY7N*+,@.6t0`I;hbzS?19-Wz29S9?E[vnU_S$)9[Kt5<Ar5.d+eRC8n&
&wuN1leI>*ZLj_)o?DQaDVaGR?HH1*RX?f_X:w/<d/[i?+n?7;8dR0HUYE.7F>Oq?#erJl,3PE)Yf<cdEo`a17?1QSafVA]MH^z];8=cFXnk*6;Ph=-(CXsFKv*6j;$ArL&
&=A9Bh8RmeaBV>EtTZmC1ANNdKl=Lkp2o:E8-U8K#61EJa15Qsll.R1A:]SF^sDdspNyZLeR]>8^(L0[<QLa8S(nS^#:uwiNFt`9XD-JNc>aZE0GKA2_d4V_g5OmeUK`Ok&
&.RT_^m63q[ZNf>s+-LNF2cDlk#RIiEwnME-`bc0w5u*nwb-;b*X`WRZYbt32VuLpe;qyn>c.R7_O^B^<O15W+$LF@u5nMW-N=7Z-V$,-PP-r31MO7,yETleSYSp2d]6E)&
&nbt>c.IrrYnp,emlwvAP4.4?VTOwvc3V7doG[iE6E(,2n.y6X2PcS+#Z5,bboNL-hotoKnru%nQ#vPrGQH4PjC;`^?$7O;_IJ0/0jeIH(Za5MlwrY:nTrE@$Sf2>J9h?3&
&M7xmOQBimz?[#ww@@Rhnla1#aglxal0Xw(0WQm5EDq>M7eIg;1_8T.,?X-,KNz72vFWffAJRLR:$[Be:YueJDU$uOT]=T=Q8AH,d`xtlK;IGuVWgFSqtBYv292yur$L9V&
&UjP<vz=MHv^j5*6=wN_Qt-^/oBeKl(#NL*SF/Y_^y-0_mB2,mosoRqbGVF*h=-aL@6#mZ11zf_dDM<ES#.wyYmPBK%]Gwt5pYL,T)=PnY.-edEE#S<E,c_*W-g*)@cWp>&
&W;VhEq3.k*nBI(lwATbc,fbSy1`MG6+#Z7B*dL8s=%N<S]E8D]JzkxG^w[7a3/Rkka-`e_)>(?ihxu:Mj9X1/0)<XJ>,ky:1Eja4_oIsZO73rwdm]))4=gJI*gFUyG0yp&
&`fKeS-(_O8=Rq2^R.UF=>*v7$?si4^dWt%Kg`e@76ED?=.ZxXQx6XOZ/8b+q_^akIV2^AE*=8Uc*_<-zcD+#V/e6=,aTH/f_Q/u(F6pKUv#^S*X$$,6WpBlL-<p*(.>/Y&
&,Bi9cg^7`t1Qlu081Qb^Pr<>/?oO.l=lROMUZ.@]Bj7n7SDqQy)B%xk4W)e.ioQWmr.hpc*)t#Pt%]Q6xTWlz]%RP[Zo+x/dq7:I2@s/e1.c]DXKO8?NX`T0T1D*LJKJc&
&,2r2@HN#/_2@Sf*vB#47L`Sr?cv*Te/B<Vz`8z0uR,@0#BedjT>:O#DN]]RXF.B^W-%[R=K/Pm2(fcc+U+e3do[yrLhq8;yG/^,XL_8]#dDIOyA2%%a3@>$suDU=/tYBo&
&A%3*L`P5_kJ_.=HD0dZ20%sx1LMtd#ZaWVRRfK1h84pLEoa6F<mPkiEj[(Y54hD726wA8Rh?b2<QU[irWW9+lJk)`7NUNQ4loW$)@^Hq6E^lmu8^$LAiLn4A,5>Si3%,c&
&L#wYSkI#rQEbBzlV-H=7Q1(3L1,+W1A0o#0Ie:7WK4O1g]TrgqHcmgkc8Jgm5H9lw]LO,oF=n6,Y=v.tn)TCJNm(Sxd_wLxMm48wA+oPgde]BbwHqOal5H(3X5_Y1k]#,&
&k:+;dx6xF79el`B@Ycz(QCMK(m(vRps1)yu34lnpOcU:MZt=AW7mbPjRwx(O40ux(sg^x+:=k0LC.>R7Kpj(U@F@MYzN/7WxJboYhA84I_Ol8+Mwul7:$gZ9s6oj;.JS,&
&,mPPyD?1+<^>4l5nF+DhFMp([bK*N5Ap<(hL$hlgggui_M)L@nSZ?=nNPR6[M9V7uxB$,Dq8N-D)$5PG*r9_)^p,7,?fkXhR`Ktzh0,p/L(fX?Tc4];:6)GiVy23Rr#Ua&
&B6sGiGtQMrtm0GL5/E(n/Seg=f4*6iU`s,p+2$U6Ak7czX]@4W4]C(,y,F%4:PqIWxX6EyQHj<MW.N=.MCs3NxmxY-TQ*?#SmCf)+Y$;;pxrY4zBMOfIwVUniA:sJXQ5;&
&#+Sh0_7g^XrnNMZu$,JL7=,;I^JXI^RE0.$@mF:CvU;3C+4WN6z0g._J)0:wl08dVA%%a/MCaw7Ef*A9]n`Nv=h/iRT0*W_`_-Zn%P:>Zd0dkMPj2kQy<N3T+dNUhRN5]&
&ACt[.OZ6V2F*gadV#NmSJ(TNA@XKGR5G)B%uM=ZK6z>vNk<`eTQFBsH_rKvRSD-4u1nqNaE[d5skQ9+,b6Q<_/Qo2SilV,+65`hijP`+J4.E0`8IWlt#1gVowrZcMN.qw&
&gHEdunjTcDfju4-1UBD4bip:/P?@:_Z9;_cdCTI>F+0iRc_L=ziAgO_$+Wtx@]PO.8f_J@4SimwqiNKbx_:w0e)T`uJUn6u[Er%v$Ep[3%$:[UF)#`OW=Y`:z(HdOz:6`&
&dqn;,Z*dQpYl@u:`=/TQoR;;R3%`80Axa#5LD*@F.#j2dc+hm[`L)O_Bsm8AG%W7[vTs[NG<u%Fb>Qg,c)m9sMPXiCo;BPqv>Cz)Lb$4B/Lkax:Q,%K;f8*MoWKsBe-6z&
&-URODgoB^(rD;c26EU$lFcUWi<Rt2I7L8EaLR(qOOy+_8qR6<bm:acY*Aj5DPmW4gm9Bd*A]/6MJ`qU;8U4Gg^OIBvDXqJidvMH<5k4_RvkFV:Z-)w9]xb4XOYh+=bw4j&
&G(@M4Sz+2d_ly*CvyKt=I1@C(Lm%s9gcOiwb,QN7pPhk]R@cNqaTWN:V._TUjicT*ba9]vB`,wutdPt_aEcT?+9_J=Fznp04ySgge6e#;K]S66Sr)4#Z-B*c)TwOiz1h:&
&G%0]#H5E]rH5U1:+hIw)n[xU.Wa=cTrYray.)YmAmjfU4fES_Bj92[Nq>4+YYg-*j+=S[-vXG9YNwM=C9e,d%[k4dCLGc@DgY1f^2Q8tU#hd4dwx%XfQ#Xxq:AP^_JxjJ&
&i1b($duinLsA1oguObO?>`9@rZ(qO;i4^wO$A?21aV8047@I$eG:Em)6>$nsanHmaD4Vr5:btzUn@ITtN$`/CK^^Fct@QK1a0ovcY6$gfgNMpvhQG6Dy6xGLG,t_31T^e&
&i*YfL>.#s:0aKdPGRkJnbxBrYNy=YJ@]u1pZJ#P]t4s?JsCtTLVA=I]@%x.S/ThdmaHEGN/2rbnao;:]xMfp.Yf%EFO#?A8tnANY1T^yoUi[pHav;q%L[X*d@F=roD==s&
&TmaOhnP21FN(H/oA`(:)P+]BZzm1;SVglTkh[<bAuI0B/[$DG9d0*15?4m[@uFR9hXEXUcizOTy$Srm8nA`^qX.A5shl3v<WJxKrtjPTO@egec^pVWU7-;_peTGDvuC)j&
&%S+l*J+gNv1k[wqMA5lP(cE0]51#i]V5I(jGu9/jJ,?G(vU+FHId^*7sERzd6,V$nxU7@`)MMT0^.3t6:A_2>0IiI)^(+/AULp^sE%b+Q8rHJ(-%DeF]Il^cy,iauDT%X&
&%AqDex1HoN=j(?LAKkw,4P8LB>%d`Zf<68AmwEeagXHmhp*=5>MmN=.7-HTH=^qSav%CA*uC6I-4Hs=inorXF:Y+hxR=dlfW@G5f)`(LjoAkB[*=/6Yaa?ZS8oq[a]WWW&
&16YCQ6I;I78ox1pA@%ht9jW5::r`ts2hWYjvlL6Ba>uaH@W519GXt,AD?x/[g6.gbv95B;L7cpgi>(J+A7(VXuSZ-R^Y..C3*SO1R5KAf[5ujH.A^(1.R_gb[)hwekY.b&
&3J69Q*NOk>=uc[)^3?[:z41#mflBzFDCK,/rY=4$#WjCp^HYK)`?B_:90%nj#)*7f,rsZ0)%W48q3?PElaQ8HgGnh81W0XP/?;aDj+uM`0Md5c^a^k*]S[ya94D##k/ah&
&g<Kg>LAW@hiN/%`S`#STLln;,y)[)T*dc:wL6f+#S^@hM[y%Q1593Uy3ofM>:Xo0IyZEnJ/9B#MZ_WsoG=?_>-Ni%@MVBXP<o+^NjD>Ze+=H`rD6=9,gbns^^Q0OeaJMj&
&2O-S*#Qw^WqnRQQAimvJHxf(HPk@=Fq,ikiVzs)6LV;g6lwtMQc>CMtBRS76c7q^<D3RLaT]^mVRGqZu5.CU%Y08+W:M;-?+HXq5Sy9cL)^.1//lZ2@zw^N,,5jh=n-bT&
&R.Z40KYgF$K,Noa.dQGGkY]<#G75cyRGu0x<r/VD8(xd>P,gNW0F`I8j9X4L28G_Zr5wWZK,(+q(@8@d5tCP:+BzGvkRl<6#b]8]Z.[*X?S[NgU1me>h#6D:=U5dUnr`n&
&024Zy2X#aiiGoomYXzjX[Mp@GwCg<u)jaiv]E77U_1.3=x$Q92gn)n1SXy,%WwCY#y6/q=A@iisQC9V^7i4/qPuqmhI.(s3;37Z/t(wB:`:y27E)as/i3H2)>dRPDU.:=&
&@,Pi^P_.d/8/@oCBh$]z>2?48:ijAlkoM?Baon:,6rXfRHg*#J-pS5vYjaOVV6-Y[`:i;>>%d0YJ-1R`>3Y5or%ZTQ3<<IeX89+8y[8YznQ:3[izf@zv*nfjK[4el1Hnm&
&DgZer6H8Y0kK,gU0xx-+G^ghwb8)*jeuIj3Y*,D1SuPTO=:F2sBqeJDZfmM-dH0qsE1;;HhU8w3[YVwOC9qe@[F2QFN0nb_#I:`]M:ba18UBfg6vdK]cb`vFTPRnb5C]:&
&Nq_9Jba,=bCO#,NBw;@cuW_*=K,EM>xP*zK*KvK[Pm1qw%li:5W)Z+?z57v92Jd]lqO5u:qJvT6k]4Q<u0JR(zYoqt>%r5*O1?`#:QdY(A8Af54m-WKWonl7l#jY/agOZ&
&AKO9HObB4ESddMb%U,X=YfT2/TDf:TP:cWTui-y:?oib/-GQVV.()#[mX^O/A0>AMhE4z)v>zf^2*fxRkrp_o_B#ik*nC[goPJoicf;<:fx#9fm(1Dq6(s(=_:HTyT:I:&
&`U*)j^4db90F4.7vPZt%L@Z(.yF8YJ*m5.IzCy:dBe@mCpY^9TqnO`a]7`UYzP#^DD%$e]UlM-BFQu714/xGEloRb%p3RQx(QCX0/Y/_odeHdEy1[*.kwj=lcGMDlI;A_&
&hoiMSCo0%U6nl4L$X`80mTaa[p25H>HoO=mlK%OG;M(ac6EilMLAMS^hvMb0*t?0W+g=MxaCdYb]ZVSo$<<wuHYRyBm1BXm;e-?y#aGnQl;U^bKDY_otu?IF%,e)mzNLL&
&4u)1inUootGpXSpgo/:7sO4V-7WZ6oJwGIt?upRcIbz?d2,(Ft^`bl33bTY*?>@$bfy$9P>),@#Df1QYRU#vr@,CL`m/B/g*i[fMlj:e#Mh*;Y)VmNS4fA@yKwoZ0f1Mf&
&Ibwx;2?1ORwG%>tSmE(ML<k<;z61mgP/A3R41PJNlJ#Z%`t>+V3FB5Q5bmw%,ee#.6ih_dM[tkeQ$Vi(U4X]lfTop]Ho5(;5asS6xZY=Kgdp3U;q^0?_uhiYtCGQhwfHm&
&=D%[qDoIM.:ec#pQD#?9@=W=H:5l-:Tbdl45-mSAednb_X_.vge6QZU-GsJe(+C#p+vrkrXms-,]7SWTYy,ieRm166$4aG=(vpuaIE/5aro3.Y4JlOP$MTXn0Y-oEpBhT&
&c+r(DbZeZ.QZwfg^lN[9qoBoWUJ.b-CKeg)tpBkpS5pH?tnh9^)g4aU^3RjDHnF-nXI-ja`L=oW)Vb/j52LqalX]T/`>q5>+%Z@9S=3IK[4A]2x$YLaRe5D.gWHz,;9rR&
&jS39DHAYaT6Lf1q#@Y8L=pK0Q_qC,WafIy%YZGD)(ROeJWJfyn$`qBA]A3q3$Z.kB_P%y=HY>A[iDSn:MQ2IRcB#@@Y3-QWVOZePwh(JGT)<Q_EtvIoOU6=r^_KC7QcM.&
&O(kVhQ3(KdpUO@E>W:)(hgno5e[Fsm]A>qJ]<C$bSeYDd:cM0bJNt]KR397YBYF+n6Mp+wy-TC.$Q?[Z)<iC/=M#7#zW7M)s7skg/XV40x;@DK;*7sxVoiXO<4wUuogmr&
&:-2r2L`1L,+hm<Avy$.T1jNH01%KpNS#)PG8lgmB-dP_f#8JrWvnBKf4^)WU1rn)e8VtV_-/n4@$.Dw-::QX@erZ]E/iHmK.x/NiT#^R2X,)rb)nRSATK?x])rj@ASNne&
&VourF_cp.c5hwqqTlN`kL%APXh752ln2mKH5zZ.lCIL:@AcxQ[j,F>N]YU?dJhpw<^jFCe?xVc^JkmxJl=FfCE[1X5F@C4m@?z-qHUTvPFrCaNrM_,mJ)x_>L2>Njwh5+&
&f1gsNt3-PB$u[7[]Sbt1X@QFW2.2VJX/>Eqy,W/@[=v,Zfc7pW$<>o0`q,$Y]AJWfBK06Ln;Dv.bH`hL)I=ls4$Xc),kl=APdBsgXkK[boo-.H:QQ]gdj;BAcY.obSg:Y&
&Je=uJW,A/RgpWlpPUFR@R4=FKj+9Krc`=D4v-`1,L%D.Em`Lb-UejJ0jS8$t=YJOe#Mp2.1ZM6Lsa@[d7e;7K6tp)Qxd(EC$RLI[a;L6r[g+SI:JXZ[W67F>,HAD7gQF[&
&#1,bfC%#sTLRP;8gL:vAL(bkpR)MFCtf@?X*8(o4c6*fy79?TFcefJ0.x(SA5I-eqawYU8S3/1K`vIuHJ<IJ=uxDT8Y#K9^Uj)[G4#I<gUnFZNAUm#2GkKG__#+Mc<nOE&
&y*c32;2l95V[3XqdjXg5qbjbITa8Yii)^?W#WAC(=[)9YnAr60nxgB4%t0P)=iwj?([k^Ez*t7gQ/lY<S11c<kXbyiGycal-c.@7=6*RXQ.]+c8TvJCE$C@:t`^qjnO]T&
&Et`V,rX@/_[FYYd@Vh3hD8QTK(b.-9qJdB)c<ceV4I7B*2ZNuM`rFV)j,:]b3:6^kCW:FtDK5)(=Y`79[)cRCG0p;jABv%(eJs#MVfXthpq83LcH)AB;P7HNSyU`%0q>;&
&q,]F*%,@dj,B1>20n=gr>ZHhH;[o-fBo8HaNS,L4cZbRV5BcN(PjE)TOvd5jg^-Fw5HvU%+3u57*ho%:>X(_7].Edn%k3GQB@;=+dBsH0Faz3Z,SjUQ.7nhj-b5kvr-N7&
&9f[dYLV>O_Cz?,_>T_sbp0e5_zZX<:<Y.ux=o@?c4%`(q9sICfku:zEbr;fvxWRsw3ZbeMUpt`6OrT)vs.@N+P3?u0UzVRsqV:F0JM:j_m^SrF^tBK/J@90,5k<T^aBQV&
&w*CMM$1B*YpF7MvT@>GS.e6:un6jkg_n.JAoRg;$_*O1V6)#N2Ogf9IGFsKlodKS[koh2%h);RXBN.N5CGG)ThY_7]kH3U(F+d$sFWoP7u*bd`ZVg1ief0ptZ-T^[.-=%&
&`2i52KvM7N@>H20?g8T0w)*-POY1BNUq<2OQ;$K7PI;S2%BIj8RxRk,yx,Y]j_SO-:(;d$co/6Ly+xMVv`D,h$O=`4,H0$+(.q4RcpA9+n-:0COg:p%Y*[(n;9aJ_o6`.&
&W>dC2bM5<M3+PovB-vI#8K>-20pXKR#IV9vjnGUM_u4-/.#`A<tO6M8F;i]g[DP*-<B;8iS]5HMn,^s-+JEwj@$TVSEI<2++d*zQ?6yzrGt/9P6c,d>ao^8.=.)^Ouxfv&
&i5wUSiU`4Ax+?=n^$KHGYL,`X[1Ek=i;.ZL_*HXn_03g7YggC_vB]zvJUAln+UNHq]uXn?FwLNpA$N14v%oSJD::`A.F=kG2V__M[o;G2JmGm,cQRvdiW1hylV>aK(7)I&
&PEI>_d]ohNabja;#mA1Q3iF2>,v:EI*th=_lk+=@y$RT=`1+cshGY`8o<Lv@:WPSRP+se7y3/*xC4q#J/]]xNTVQUe]P.ntZ;PH]Q@Cc,uX/D*462z$8YmTLShg/#,_:-&
&(]TCf^Sgh7Yf#R.Qe_Ki*c;dM+kBh4zu55HhM,mdl.b4[q/#Nt(t.=2Rb[7_+QM1?K7h@(eW7/;OKX-vm3]+HgVue(0gChb;-QC;WKxR5Ml89f(RY,%aDYj6C8<[cV.E.&
&p;JV?qDXv9$N$h:;BLKozo%5GkudSZ@<o[GS-hIOgdHNarvHWsGlR@cf4$R>_AauKNg%j+8+I(2yTbK-[%Kf@p*uxP*Ku(ssGfS$eU+B)^/LT^f/xHd9v9T2pqIk4Q6#T&
&RbaZA-g1LJ9lv^a(O0to;csQ/rh`QU(K].W>D%+uf*n7MvByDUHgb+SROo+,]qTwAp^^Vt4,cRso?.,vG:>k-<(5pWjJI(?ha$CSD%^ibSh;1r-I,/V[*eM--[$?1>IOh&
&XugZ5#%mcLIAQ0l=YPanAO>V0G]q`$QNUw_q]jFKCf`y4U>8^Lzw[P9z1KxxlF81k,pyCp]clJe=)A#%5S`8/`]xJ?)q5*=4SvA7bQDzK-S(_W``S:Y.7W1ztmLQXP+z<&
&h]vETLXO[5Kr>d`MB0Y7TE4hGC3pXX?`SUA,)YdFMHMd%-USh`O1N9adN%CkkBui2l9%T:XY/jeTCN,WZb$QM%K_o<=Qp0?yl$Km[.-A4wV:bhXpQX=1e=$lr_?ss+lNP&
&85[egzK/<s.:c*(r.v$5Vn.%j=v2J+xt]@B+BRIPF8R4yhe9B$HS]53cWg(Kc#l,x;Sf6>FhYVt%Z=BnO$[1MEM1lhj1Qaq)*Q=7mbSN>eJR@`sEQ9w,6_Ixj>FBhBfN*&
&R@ZQCGZV`7.n<?W4wn`<>6YQn#T4^5tsyIaA<I5S@o-P6=jIq)vWM.I(Tgd5@qSJ%x>WzDGFjaXR=scrVAeykHG^_Nb+qM-l>y2^2=@]B6IN(,dxoI[sN-MR7t>LPYb1=&
&kFs)Z?wDarvlypc;mD,sP/@U=?j4%JQ*.xB4B)0amx[NrgH*[`ZB6:kRGP*OfYxB?s8dKjI3#l2EIK.jeisY0TlPc#/FzQ9nw77[cewTR$2_47,5iv7UX2MRB9(u]kYS[&
&_an`)G6]0als6ORnhdT8?GK[uzJCaz*A6Oy7+IXH4hD65.t^DjZUpaCU<K/dzo__eNWGC;R;+9M(G:?g^(eZB4fFtBq8SJpB%o7=8XNi8:#e_Q;VmeeM8B:%KdRp@e/j)&
&,h73#QIq8hgtaK;DDpw4$^(wn9DvEA03DC1xF4GS4.A%fWldnN`O_vaIB?=v41k`k$bcz03$vha(wht3-@wRVW4F$69o$8<Npl0ivhr/bT-rKCbo+AA>]>9$v%`JW=_qV&
&MULsP,;2`)TVToN84`=jwEwO[z9#G$*NFkAzwaP/F2TM3z;9^]HPLnMXe`n(x8oC+=RH/,_gi56sS0`+s,c<p>n4^7<fZ??@t@sO%RcJ]zSZbELI9QJ7d]TY9>d29oQkh&
&`TD.tyuPnhQ[/Fo1;pTF?mohfD;29g#5QJrQ)_w>?`+ahv#kLaG;RH^SZ1L=XnrT2W/RjD:-M+*tQv0#G+8c#E@I^:j)_lIbvYQozN%.>QTVuGatX$r7IRk/u+qccBe??&
&X<#OE1RtBaKrLu`:m8hF%Km@p*/0.ppJ-4WS6I:;SJVu@E[XWHM>V`7$p^:SbYdV,wIy1HPDPY4Mr@aiM#L2C:wtIs8R-@^r)m?a0RA+=wqW@gCCe?5X]<CwnK@bC0,EB&
&W/N;wUWxLvuA#IJgnw<pFpIJ8h;p,L2g@`RfDaPVT)3r1XI)9g[4GUq492uabb,Ia2]CNv*M)5@,v[Y+]t(MI/dWh])ANE1Dc-sb/mKJr/;>SX4%)e6xF++?`7VwAC7#z&
&W;`.XA4@:@kPSUXEk-5Dx;)2znrf%c<hF^4l2/U@87lSqVRck@W*Dts][,Be$N.6+<2`_/J0-@A80/]q^v2QDmB+XULlR8T$W(Fd.4SEmnIVTMVgn4vTP65tuU5Uu6Rg^&
&yO8B#h#8*T_cj?gZ:R<g%-b>AlOR^%5vbJ_06kbWDD5=mbIGjn?W?X74V+GhY>qn(yDC+*[7`rYY<S>Yz?tp>y<d<>=bAVDq4-m3>M?sq?z1S_GwbG+iq.FU/acbKaQQ>&
&:qk?GZR5l$OL_V7#zW;8T0rS3:O22D_H`ikC-:ZFjh(%B<M%-L*iSd)s0[A3^sy8TV8;UVE3aH5R?N.sryeB%YYJL*OK,MM+*Gxc7FPy)^hADdGcG(wH9o4Y(Lkt,CDST&
&L,XDK_E;;7>G#DXSP7SyeR7b>ZCc_m6k6Q0l8jI/6xrQ(=Wc6:)u=B#=.-,F8)QpIR#7F)LLeOlPQ]vviDR`)i:bOVc>Szq+uP;9w(:,IY2I.l?I<p@DM%aZ;RNkP47W%&
&EUX:[@[zq2$ef1-#t$N:i2ebzQn:.>$SLcZb.++:shR4_:;FdxW/]jhb.LyZ(1a;Qm*BipC%H4).3+aV3G)wlP`mm_,[eCr)%+o$*V+FDC(A94Z*px7qHgZh3O3.$oC2$&
&qw8pda]4HSbuf+zAVOMCb=_Og8VKYmJiBGOc+_S+as$BN)t?Q6H[x-j^YIGo2Uj5V.*olBx>k%5sl9NVa@MG2qfQ#ZvM:k9oMtS.6aBjd6dW90/IPNVbf2>Sq,7Jwra<q&
&HQqII9e:KT(_Ri@(/frwq84@u4xR^#_wYkJ4#83@9TU3@:GIhb_^X5Z:wUx/`4HvHFSUU/Mj5243S5pkbuVJX0ZO@BHQ3tFQ=Hh0N47TWWAiHnee.qpy2RM^#z#AGaBk(&
&nI^8JmK_H[FpbeKp>*a7A9IsgWZ5o%A?e7lpd-C-4aMAM/gDXevXCT5-RgSUia<Cg79`hi%Gftg+N0Uds+H^punWR_EJwn4n]G9%qsJ2/L88vD6ebZ:/;zr-0cp0)xD-/&
&kym[gA2$9N4%UDOM92F(UFdXCg;i7KVU/8Cdamdc/@i2;8<iAxtVkq*FqOD=)UfaJBbSN2@6gx;#3I.oP+#j/o4,b=[Qsd2dev(BvUS^*=O2x/b]G6k2LJX,5wb*T=tqX&
&LiZy*5PJ%X8=Y7S0h.@OcUi]m9,xFnjC<ejCa3QF2MA0<qYBR1gPQ^4,_;5HSkK#Zk/xPar.uQ7B*@Lal:HzDWv:TJrV?s4PSGLv(97U9I:S8v0oSmC`d<#Hrv,k2GR+2&
&%>V%ReF_,o+BbtNdQEcLy/(c^aMO@CjhGP<)>QF4$XE*WlXQh`h9a#J,NOEOH:qte?Lr1^PQ2.*?R8tAQ2JosDCUMGUqIbAzKQTVB=SxJp16(SC,+9E?TkXD@jpt2UeuH&
&G$csZUv.1Q89dP5J*F:;N(P<fF:t$i4f@KyGB7EgAiuh_likuG83mn)gG4S?dDOC$hJ9GJe2cl;0jy+1ATTtw0dFj>fr2^w+Jc[3k`A(osjr=DqceU<aGow74_YrEFb(3&
&Ib4]-A77zV^nTvYm9tTCwy9fm).(#Y>>JtBB.V`^+5%xmR8#7#UHQQCLHUM.7zh+3AUzJ.Q0?=r1jD]^5xrW2nDoCgh95IrS/J+wEa423_.%BsE-?e@<GkD>HBRh<Sx_M&
&Uqjiyw/,XG6izAxaj*IgS78(Q;.%59`QLi664D_ftW2$5MaFc5%qm/72^AESVqE$9UTi]-$yhiOr^3Hi4W6Q5=tPir-zJ*BT>LG@duC>cPxuMg@s0EGDtsjIPnEEO9s%O&
&.b/LCb7+ze_[<V#$>:Z+s2lbV3)y(NG?j]jJJ22pu_tag#HE]I+;lI<cf`9_1M?oaYu^M>4gH8q%hkxZF/9CdnFQ3`2K`OYRMr/Nqt;8ZQ$uIpF$Y.C<F1mCP92i-iJYG&
&3TV1kLFD%1-RZ*GMQ-Vbn]4KT0CFOdV/LGoGGgHJeiaMtv,7.dX:tZ<U<M0=227Wk7-U9s,mVE(2ug$$8[g.?)?-Xt?]A2R)SqAIo_TuY)D5iSt5^DY+NGNY23MINP2Tz&
&3f92JYW;2TY)?P>kZiO,,]+$UN+<g]1g_.y+RkEjf<`Y*1]e?b:VEGDJRN$Ym#)KRV4A6N+qcvIu4Y-%KMum(gIjf15#E5G#ft?wq.<HH>aT:pF]xR<ERCV9W<F5K<zBk&
&V$ns1Cfjria-iEDZEH9;m4*L5BY;A;ZABiTfjS3wTD,c6Fl%wQ;9)AQ3(iG?v)9Q.^Y#%<TQ6/T^F9zY<ODEAXoHmXji7e/7SoF96+vDdXr9z#Q;F*?9mYo*tEtU(ax;u&
&d>NVdV<:6>^-uU9M0X[KJkFa%CT,Je1=ry(Ta:ma*q$rnK+dWPsRa5Xm5xCqp[yK*Mp%Wi+33.:k]qh;Ab6bZpgsB91Y7a,ba55B(;[+R,.Hyyb[vU)g#WP@BA]IbTW48&
&+eBiv_hz`qpTO-OG7`Asy:25tTg)[dui1]s6<kH*LgZx+X`-<5yE+GG40wJ^M?-=n$g.aBB[K<H_//:VHMZtfTigR(ck@zM>tC#<h<a+^RB1FdxBd^>T9+Xn?`]8gM^w^&
&UuDC%4<pOkG>o@wd^4TG:X4Dyd+a9P,gME:yS7dWlLRRXaU>R]yI<-(k2Clxc5l-X%)Y6XT*CUldDb<t-1t62$(F>Z@C2gkW#K+S0S4@[(1@IpDXbkCQz4dB];0-zw8F<&
&t4[Xv>tkE5yZPUL9%GIL%3EE=K<:uAak:t_a>T4wN83@#E7mm.>KAM65OKccXfw5h68fAo_@[Ms+B5eB:00.]p<4,039rx6NBHf3,I;x6BROX4jjY3PrQ3GeQeNYm5ZlF&
&N%vE)3YkxU5WdCNZ)^_AxB-5cbWId%JM1$tL<1__sdR4p[r7n$eF=SCtm5K=6m_%$SW=XReSev5wt>iHK9Yll,0v>Mg[@tA<)^P@;gl-d7DRi?oF8H7alpn4PY#W[69w?&
&J-$qWcUKpE_1J:2[)kI/ZXZ#J/9b0Zo)*TWjM#T?Re.8:N)iRmob#McaBd$Q40Teftr(wAh_%[YS,V?,V.pe4d=GBd*CxtlEg8>pdzH[RoSB(+x-f?9gnI=y(WED25[xM&
&s0G[7k3@M.]SL.oOO.]3HY$9^@]DtVD:>B%*YBG0AnD_Wq)Q?[*Qsb)a>8n0@e.B;i*^hr@+=Oq1?*Xt+O[,w^reVTgs^^Q1LF3b%W1EJfPv)E*2s/[d1V#g</zG;]([6&
&Yv?ujc9jNRuubv)ZXp]ICs@CeT4P7of`>/Ri,oT#Q;`]$Nn;B+w%l6;g1api%26u?(y[+2TYWqEJ+7W3m+[1Yqbbtj@bIMRE@Tk[PjPWq)fN5Q)8IaCoDO-T*x^Do.MAy&
&Vk)mHuC_@`?tVF1Vix+6DW<?%],H>rmbN@5$wESGs[6eEyDY.Vew)tWSl$4fzT+>Fe.kguOiz<r8YrRE`9x48hmo]i6piK.X[SFihBD7_/iMX<LU77daKF=DCDU[RgR#N&
&PU`0R7<HF[B9wJ$2M`OXc3O-U%fM7gCIjJp[/ZLtb`](U8=vz(N:z@<RQzX[p*JQc<39%:)K>vPMmubanE`bTQ$7OnjCvPf/^Fs;+cEoCuoPR1T8v#nzX1]bxs:1[MKGJ&
&KZTb.=bk9#j8H2eI;b)e[KbCA2U7Kk6+*QRLu*`.F]5L6DQ;8>E84nV0l*-B2o4/p%Bt?G-TOq-,%.z<G?Om>O3ON6GR1rNEXcSfAvlFW/jEM0`t$F=iFE69gYHjX`KR<&
&=NPw?e-E/4%REA)h:e5>BAHs5@i5JH:-7Mdvo=h@-DaxgsMihOOUa,m#lIj5$=l4vJEMo/.FdTRh#yQMOTSTdi<pD0U5rxE)(FWdupur)aU0_j5ZG.V<2RmO@m,mT1:SI&
&L3h:AaKMT:zZ9(c];_R.#k%)2ylN#Fe-OZ^n[[Nl1ze/z*#V@ugKuCW6f2zwvA[=%oCG32auvYrqC*=Y6p+mYoMjI=nkpnO4jj8jrXGHhr`u]VAjTYM1?Qms5>RVf*m;2&
&QDKQdoJfl:`zu.gd7t^W8li2<cOi#C`b<a?E.6Q[X>y(pDJ*k.S4gRLc8AR-CG3Pbp]3Ebh9f9]p:Z:;qk`BsexJD)qXyON(bZE0dE:PKIB,Scp*t%BvlgPsb(.jiia[v&
&G+,BZ(M=:8FJJO:TK*:[<wUW%p4G>w?+5S@X4@gUMnN7/(K2JQeE>oPH`mFhI)vW1FSfv_Afg#=X];IVyBYQ<_9*#6JU+Qw4CkN[kXj%5@U*15rk?;9rrRhdH^W%7mQE3&
&=Ue4BIhHVr_^7bD/rky=eG9?-elTbMh,Xdc+@Ov:4f$5#X.^k]>AJ@M$?Lk,E3qNI4N:Ct%jPx*V+)ZDXU>ybX]Bw9Tg`?#oAV,WH+Kh,XnyLQYSeDS3z4DRnO`56gIz0&
&YmR$Xc/4xqm(Y/Y@:]CQ3*p5j.dH]nl1:](2<qs#5Q%E3cFWAlh(p:sk>?Q,MCx=skNZIK0AqQ2h$gYWYp1[),v[^G:AOaaRcnR`O+@pgYPp8v8@cxK-,OlS`6dFMxi:D&
&m+s43#D8b%nO(B0.D7cSMXg:HP9J4(z?sEwHYU7:@;pg%/M<Zls$dCWy#Q/J/:Vi_r4bN%gNw=bqm9Qr6G#3+6^_8c,FLYjaa+?Csn)50n[)(]@iAKTvc.QXWTOm9RFR9&
&DYnJr>Iqaq(J9AN:F;q:qFA>]HK4^xRWM13R+wYQ2GL[H^U9X`>X:XmJza7k[;2MrRXH+Nh^*[V.t$$2c:B%g.GsE@+%WlpWE=-FYw*/nCbWA@tf#-+L26(F[NkS]/(IG&
&v]0MZD%3CIvJ;:YH5k?e#kWIgaY+Uo;/48vz8]v9DA(bx/o*6aS;Kjg$pH)+l%.5[s[-z)[xmj6s0PWfKfh0t/I@zEt9^UI53+_-`yG6pItQcZeYk,U-Qj5%nyj2d(dQN&
&:V<#8d^/w#DrdQzqdW1m=8Ci`H)BmZq6%.9WUEC.:Dt05njj@a@rNYx6KikvfE>^dV-PZ:he+O,#K9%ntu>gP))<b+=]V7%)b7M%_Qt*F23on9I,8/GFZy]LTY`Hm#9rB&
&50rTB(YNXvd9L4HV=(Af7+KREUi`-:a$eZajU?(.H0Ef?Z/NdSY/DM]h/a;[4<EhtYGKvP,E4/qVgaxYBEVtHR7VwCf.://jR5D*2vMcjsSf>X/)bbF$.8Gz[*pO1$J3s&
&cP7O9:Y-.,y?t_kMk08x*;^/DbY/Ka23C:oO-WHbo^2M>.O:Z<xA?Mqb0e2N]o#J@m3n[wvi)-2G/b`nRQW3h[^gls4R@+AA.-`j.DDi>gU$QxmV4.DZC12T#o#i,Pl6.&
&*xdCv/KPf2s7T5nm8aYlE5.#Em4YBtUO+ZnNTf6.*xdCv1=,jIi@xjI<quNNsu])fA3]@8#YG5GbpxSm*<xNrA,_0VU6+WIiRhEO?6.L^D#)0MR#28`UVZlh@.c6raS:b&
&-f<2p?tdw,Nkw6@+zz$4;qg;[Ut[o_;L8$8;PsKLRtY]jIc^UBYQU=r,:s+6r[/YnE`r)2tZz+`cc,^NAZpb2FW8sbbx`OG=R3fS9QGkSYmgGqyx_Z#idDWi-Z$f]T%xP&
&A#wuc-EAk1Yg;+?5Tobg7Bd1oo]PZl[IHUbGN6*KTlG(MWz[Wiae3nFG$3wTNDCnMPx#ic#-JBlW4Bfq7V8a+s=+Ip6:mUG<m]rz.+4(kTPl9u5F#Yd9jZbA6s:W68(l<&
&C*2*GA1YEAnk[zbZ4P-fw[vm31UnHMK4WZjWe1Oi<Pr/s0*eG0IqEIeC*L^fsOY_:o<vSMR@e%er6-.oLP_RqN?4v)XiH]wt$WLe5XtXrPAlIj#^$tpJ5f_Z><:q#XF/d&
&IRI^/B5C8IRd4PQf46D.3$d1)gYZELKr=5#tN;a0+z;i#j#fCB/TBR7iDT=3zACRlukpxFl[fAdvOwM53ea]8EPSGI(H9yD5k5xY?Cq)cwRv4%YDuj^La)zhg^En^8lZo&
&Q5[fROg@+#Yw1P:H6d*jV]IEN.,vjS>)NEKacmhqnIcU:b=co@uP6W1%9BeK_QEGW]U-YtcVSigu]NwMn.kRhj_5%?R%`s#Cm2.q,JNeOT_44weLDB::?6mk$TyLsd-ee&
&2oQT.6#rtU;%taK0v.cGcD,lMa;YG@nrj<R-9B-K<eDE%cmh(p4=l).=xwE@ulg)6-sn[FcMAvZkNWQ`hc^qO<xswm0fneHF/VjhNqBxGa`4*hHTPE0R:BOC9uQ+0@T`=&
&iF5_Au-;;EpmEn+r2FVp^RI,c^5Wp]3zR?d@SB,BNXMoH*Yz[;l[%/XL=5#SUcn4VkIs,XmQX_Q7o4T/S5Xn%uT</$J%qga1XOWhmLT9gc%Z^a7^_al7:UwO_Y:o^tSQx&
&2%L#s=]?ENkjA0945X?tv;Z[s0^*W,c;P$Y]CyiP@h947P>FLHJQw407,[jbhJRm.qmiX?0k;JgHLH8gy(SHaf/vcCB1sgk7I(^hpi`a*Z1.YtE8V-fI_lO<zc24rMrY_&
&clBz`gb%1m,S6Sp2OMm0ziMC8#eX=/Y?gVP/6ak,If/UMoXPr*,NJmSrS/#G0,_#E5hnN>AKZjBH3PrZ;Rk_X.00B+w6/n2U;YGabmLVnzuB/TjmqWV*U:F0]wZg:WU/w&
&:$%2lB0v)kFx/#jy(3/#`Ser0]lb+QT6iRmTBIh8A5$SoNTF;Mo/_,#yiN_%,2K+P:eyQC<[yD8`B*iVq;l=4c)N;4jb5K0*cd0h.gt*q-,z*wj7`n(/mrLe5ARZh4.W#&
&ovvwFPgZz>wX/A(R+1/ID)GIA.74LEwWC#YmT)L92$*kY.?X/_hB,.41VkP0@UQd6$^6d/[J8824U@aEiX9rOBT=W5cx@]S,ggLHymQOV(P=$^@in`/,zoY9mwk.fAb_P&
&Bbyl^(T`]T;i,x%l%G##:?J(gM:>RknxLULo$eAdg<FS8CDU@av]uh=/u@F>DTO=fUAb(aw(lWwi)h[8`Rs6:(1Vkq(m2Xa41%bKihoc,c]i`46WhGE0gTP`LoJdK3w.?&
&/`O:V:8+82q^#]f`c39=oHM4=p(*O.RkOw/z+=YE2[)faFOhFYM,`eeDiS[[;3G+Tbrrr9P*uVk+)#V<G[a1dGAbISeSFH^dUzJC1+G:U)dVk1VW8VHg@U=Vt(RriT/]j&
&WKG-_^DjTd,hZqaC)Fi#;21j3e+7+`f1)-A*r(4spp?bR#<HV7)nJABcpV[Te,iPmW)5A3fMXZ=?lLlha2:riq*Cz*(=bN*wLFqky?_ouW>vY%ppF_q0;_oY.XC*hJsjb&
&$uFDqZwBha2R1[<(Wb-LU**]XSxA92#ptH426[NTq1/mHP]>4c>4bCP9*.ksqm<eqI>b]S=l`JABcpZ?Cs)gtoD:0FYoz1U:bC5+Jl7<pdfv`jS>+dn[:=@>zyy3P7V8m&
&$@)SO/0?cce=JMXhM.bqBw:d>$K3m`%kcd_kr2EUssvoX9wA+OZdzS2?n9;6i-zfnMW.9NBma/8yn++>,tqp1N7/Y=7$Vy[m1SoeQE2Qgg)ny8U1<dkN@QfJA8.;m/Zp+&
&Q;YveZ`S%N.#Nn+iPmW)5A3fMXZ=?lLlha2:RYTH6^NBlF;<jM0wG@2o2Q?:Y*+c9TehLhhkgF.(=[iyG/)QGrh,gq11c4XW.Lw#;7+,-`Q2]`Ki5jDSx^py>+e;,IUXZ&
&BiY13BUJ`IA9nA/U0ewM*Ji;VR-n*pzXeMQ:8vIj+]W1`67]V75X_>9kkxqqrJtD=3RVF^^Qzoy;%QPr:=PqGt(8UG:bBwb-69Jw#XYwQfh,w6zSRXg1Tx^(aKGm[j#ck&
&fU*@`]8un?Ll(rtEY;qq8W`%0((w3F#dSus)F:::r=jmL-Z<,/Mgn0zCx(5f8RVI@?n,:xG@[Ll1cM>jjtP+K#u-Wdx4>y<:A*=z-<wvM@,$[jeC.pAz`Z*^XGoZ`*RDZ&
&.du<o4RcOF,=$#M])U-d:fV9]TrY6Z5CpEMjaSWtFbr;W.yF6i-dh+/lUjfhr6[XEld5g2u91N*H`XIApMN2/xo7I5-C0rdeAPa]rq6Lj23yCnAn3m]+2[m^vt9sZmAYD&
&NI.o;o[_[_8t#qY,MELdy<MHZCQz8l=;(,N5Hjm2MsGSk(UipASvN_JL,aHQx%q^VT[K6$qPS[$Xdf*Q7d<p8+FT1nMDxGNPPqb9w.L_CS?Rjj8Bk8-AY$[hs:2VTYVFh&
&LZI,9B3xR-,b.jPGJ=R$<kXu%8b:-*YT$HAx3LR^65X[JP*Wi6+@nleu*nsv-;_in`)oCVaiJo+vJ;LHOhFu>%BU5(qdPXWQ9[NUkP_CJrQLp@2Eow^-ZDHff*stlFxoO&
&jFJV4]Q<Kl$e(9>/F*%1Yn.#zzcB]^$Pzc8bA(<B<:UGl`s$Slgj%YOZWNA`Qs5P%S]/T:.fvlI#>?g?-kzRl-7-by^8nhkV>KB:Hjj(,V9@20ChR9u;Fvy*EW6r(L=K0&
&bW]l-b*2hF:mQQ]9Gv[Uk??Zu0JVfOu6pg<W:(>b)V.t(JCMm#VujD7BXcLCxn/uGE?9)q,^OmJF_0:G[#c=X[7TkP?+1OOj<LEM+o:Plp0%KGogS6:ku0w/rzS80EK/K&
&,5<=ux78IK%]9$ilonWAR4UwL$YxNfm:)vB9.Z3$Xp(iJ=<0)]e<cuVLsM/PApx=--(]dL;NO^Q6y1SEJ*>CZA_369$Y@;>8w<wubfEPie,LKe^POI4wmFj]x9gjv(E;k&
&rjLHvs_uw8i[?>wMRt=8:LBa6c@d+S2-52c/ut*03^OH0aQ-a3ZjAoO_)vrM,^,VmZCrliS2-_$NdA746zzZsVJy=EZ_z(l4>/Ooh;%>AWgU/mjMq^(+[D.OqVan2jr/9&
&hXvHJk:H?>SQqip/p2[hjh?w`Y8TEg]VVRq/YNfxu-)08W<5-gNTmnFgeFi-<*(FV:(=-RkxF0SqWQ]k??*s5SDNK,mcZfqSP*r%oyw$6i]QA1]VT_FZt0zSZjP(pBJ)-&
&ihHCZYjU5nVDzg)nbookd`I#B9UiVS2+#coilwWYPQvq;0tfc2gYhwtd#E><h>:$EfnqE<><AayC6`R)6Dm-o>c+U3P[)S-LE`6/Fp;qB)8IG=jqC`>?fp7p0^9F,zfm6&
&P7rRz[)qr)WK))*4$7RR9VMIoQ/Hl/`Da^I,NsXc0+UxxJ2UK;kFD0fO;kulcmtz4e0J`SikuUW(]N;p>7OCg+Z-=?%sV>V8DEJUUqUXK7.(>dlqc<)4=MquH<0*eH;h(&
&wGtgDsCOZj**%Padh/nlYA(<r7P/RckG0mdN_^js-*k$8h3a=^wM^bxcs/t$v*=okjk^r0L7McrCnoO=*3801Rr-DK@Q*66C9/5Uu3?J2>[e+kDC(cy.N,)00duDqBO`O&
&/fmaa+hfUZMU$E47/80?mKjXa6Yi1U4v+@9-=mC:;m4)?DTtF%_sun9q?u]M8z^hdUX3g,W4uc>JH`bMtZb%?HxvudePDo:,gd4F6rU5-<rP<n/bvw5:xhPFst9(sxM5[&
&1Rp=NnuM>P(4hyPP^,V=X=9[/8Ok7.K`<1$9)8..RU-$OvDlg)YwonC,.w7<#Tl1.Q_@7=MlPk:wy([7no=iGs9]ZmeWzGFUyqsc<Z-Y3o?jf-gn7cZQF]D5UKn2,2Nrn&
&M2GQ5b#3cfDE<L#4gj]=BtJXApS6:_?>S;Cm=_1CY3bJfnnTvGBY(;#q/Z;.$YLJ#r%GnB*akl/rg>,R50O.Nygsv,2d,ebgcUXU,o,*APEl*Hy4JTi]sIg)Mo2-N9Sh6&
&P@;b?N/Pr[BS2b0o<BGMT.2c2Ri<Y/)4`dx%+kGqBR%2+BlbN*j0[Xz/Vjz?<fn1=:xjfSJY`HG*xIQr#<%Y%p+Vq>%k/Ya%.IWxNHEyQHjLx(u^McEZ]3^e#p$Y7*Z-A&
&UrIAaXG^5z0xK7bj))>ukM4gVrvpjY@pNJhu2Z#DppyG.+pZuHR[qJ@H<G>fizw)a)>XgR5f51*`:/Iw%@lNh6`TS`b-)=WSrUS`Ru[T3pa1=de;o41]zxec4IkhkK@s%&
&jhQYT-8i9TuFqy%a[YJ^nA)b.p5j<X(lq>OV6mhKhSxL-lBK+]EWLv5.QoTn6EoTV*Mz(K*.T.s<[]S65z/Oa:>I*E3`64[@mU1d)kUcoAj*qgQaKfZ%Zr,rkzD#QCF$M&
&e2*;auN`XW,<ZpcZSZ-7:*8;mV#+O,d5i<iG%t2wj;m.B#_C8KN2cBnJeSGCVEZA+)j`ojN,mUeHJQ>ppRlKZ4#SR,%1.zzOl-njZ8o5w_^1^18uh@(vR)kfvz3ves`V9&
&@g[hq?,uIB,7IN[-E]>k$%2$nWYWRd`0a-_Y.r=/k4a$l71MxdQ:_3Cb95t=nY,iBBg@ENjSKoZ/Sx*z%Ra]oxN461#/NEuh8R[^`V9DPy=m@[-OBh;Ybw;b-dbm#Xg+W&
&yn=Vgb1O99^D`0tU7G0XZV[PZ>(Uu3w%O@+?7mHO)7a8k7lOFrhVx$KAUcvYCqb>dE]j?/m)8z1C^YuQo4jLErWbA$$vHu(_i8l$((``b(3Uzlz8l,hsnI<ViXqNq+A[4&
&bcA/^NSWw1fmwtyy1ajuMHM8%:[SWWPB+d`t2Nakbo+C/X*0]OxNF4wunptu2u21NY=bo@qB^DO8ubD?N-.A*)K5<;r>/UPFT8_S2d_QVJvb>uAI:g[U1i5z.x0=XiV/w&
&oOW)4*x1gw<djRvB8lU*o<msaEL_I/Js#S4lIV>c#z7reQq@`[QcWTSGBx_;PfwG4Sa@5l7Kr:6*b_zT0ac<uu*quAc/,K)aQau/rfaT#MzT#b0*vgf]D<-IAU/A,er.Y&
&0Gk*CSVOAIdO1%%9R-FI1grp4E<o7BO[fQPiFy3)7V@^Qs;fLd=H,VllN;0nTx=+dE]0[#(T$?]:hIfR28VxFgh<In8]OhjA0q9]ENsNs9hBoO%lK+rPcp4yUp1^d1$sg&
&jQ7x,y3>yy0,NQ;%-Gods?`uatHGBAaqk[iix;N1.7BE$((v5K>23Z1mqDG,Ye,SWhrno7BfVS$>QzQJRv#s4;P1KFaYk;(,SnsqsoJ3lNdnQPap=s:N;TGfA,n^V:uLB&
&ExPN4G5CVSUTwrx$F55gfE3+ae;*7+(7V<oz-;0_4:l4T1J>KbCm(Cv.T4Nzpx=pKI+?#d=]@%A#eggV/AujCNfQRLs)cdE4H#i+qX^0Pv;kf[fQu?@z;Q>Qt/vI^lQ>r&
&Ft`gP+I+FBF>o@B<T+n5Q6wMUN*Sc3[mmT%-GEXzh1n[P8;rmhvORx6$FD>SjeCfTcIa(#ps$YQ@5,J2]A)n:piKZx<nB``ph:m@VqFV9)FW7lhOpi8la1mF<I,R/U^b5&
&*_*v7R)5a[l%EFA,;@==/7$mB%7([w;T]4kC;@R3dHw_vAIBcs+cq<ZqzCl]Gj;dV:Z(C1hK*$Xj<0mwk<CF^HC#8eX`@vKTDemBBx.9Q:4[iKzYp6%,1bAU?P-,>+v)/&
&@$>TEbe;due=ggzD?KjfdI[w(w*)umqPChTC3k0Q0?Z@OCa[E_V;PWZoI][/9Q.QT3O2cfbtN6i*I96TK^rbhg9%N9)TrB#i+b:v+PZF#)>1c^69?-hk?`5/DM1CohR^_&
&qwmNFGaK?O>6#a@*O0G@o;<Vs:D>B6j+IGv-RbCO@gr,WGEHMVCCDw,QhleXiqU#ot[7VHG@v,o]0b3fT2/ZlntKR+63FgruQbmpn`Of%G15-21<G#>m.a1:=j4Mme8BO&
&Q3cNut,D+;.Ap.y7^LU^%5oG+g`YBw^O4kIU/M3$uZ7nCZiO.o@s2(l=WV/bN#:)Bf>=^/1me-E.0Y%Cak#/vq5k-WR^#R@P:t4AkMNEh))V2v9*n,@yQ=p]buA?^>RFl&
&rXqE1b+G/NVjSQm8TV(-pCcYB[*4O(%aV[88SYn9t/,;>_p<XO,QUq[SH7MPo7t9i-A@c8b15*`ApyXyw7U$S,Lp^XUg<NSvLy<v)QQ[.)o:GEsGaUpz[jD..y[f/i6;-&
&9j@gb8)dTP@s=j]8ZFbDIU=A;Uvn]SIg=tq[ST;#(Do:NATY/QCqgx/kQ*nWYw?,Pwv/o[4#.60$[h6<SSpjfM-i8G9I<Afx]1aXZD(uZ(bft2DH(SY1gpi(M+B>Z?WWI&
&O($xm<mQbaSPZ)Iq[Sa7#############################################################################################################&
&##########################################################$0EcAMt>##########YBqP_################################################&
&###############################################################$IXw##############################################################&
&############################################$IXwN0kUP######################$So:Ii+v7kNxj5<t2f^D9qb$YugW+*__hnIIrUrIUORn.?ys:VI#+%&
&[3IKCnY42PGLmu-GLEFfg.i5PGFT24c27o######################$O*lsWE.C8M>f766k(QfRvn)_3AmU-S*<o5<T1(</(1d$.R+i[573Y19LNur/?8Q)Dd*9Ka^i&
&[<s>bSDpS#`D)?+/=Fv*[-h<GXfsDV:nrwTtP4Jb,7Oflj2N[h;qCybD;9`K*lj?f,Pa^w0gnEG]#55kQ,_,_dX;tp0%+ZJ6V8YkfLRO9>HtUfjvJ74+N7zv0uBg^$]Ap&
&O]B7c0v/kJs:K*P8rWz.%@s=bNM63YRA%(/PYIyUn,/o+$6NLi<Z9)]l]E[;X-3hYVdexNADY6LpK3a)Toi7(>CUHJbC)wG4,gOI4/=D8M$xYEo]-vmys[,,N:JR>3u59&
&n+UJ=;pCU%akF2F)<A6tsH-GtC830C+S;aab[ZwZZC-:W=ydZ%p]HNdL^`a^B5W$(FVHd;.hC**P;.)gnH###############################################&
&#########################################################################################################################$P%=1miN&
&0kUP######vHjV################################################################################################################$rQ&
&gU)ZG######################################################################################################$rQh6`mI##############&
&#########%A0vFGlfyj*sQ>3Ul=+6NgE:,Y*j:g]`-7xTyJmg5ojo^f[.OCPo`C=5XZ8`jl(P[.l[KtG_q]qcW@fM`rn;^%f#######################%*pIA]FGCF&
&lrv@Izv_@aS?E>0u+srkdlk>Uj%MT6Wb^)V(./7SVx_H)=0<171D3=_Vrl+8^F0=a64?Q1fU)h7$1;A^W[OYr*gjvi8cXq6hF5(X_LCtf>Eebk4R#%8$;A`k)lejbod0_&
&`M-Qp_,bQU$.?YCO5LYG*[8[8Jl`pm>wnQGxuWSzzh=vh]-bFJdKG8K[3,#(o*gS]tbi_L8A.YtKHz0ltL1FlZvN0j4.Tne?zEDUPCkhFl7HCLN)YFw7KOV8R^wY9BYfZ&
&U;2u3+?h22Hnhw2I;t3l71zonI;T.9/fc.M$6;t#);(ZXMCSiR:6ho1z)B2,9j#HQHG%>oHv)2g.)zb?*qUVUHU+sV`lFzQGMlA[%EV2Ophf8[gRk_13ywTG=m2vq(4=U&
&Vc3`Ui=1o;4#6SWbHvu7#############################################################################################################&
&#######################################################%#$<514I?,U######$,Cb#####################################################&
&############################################################%QO/N$d##############################################################&
&#########################################%QO0AVl########################%bZN4wSjavk^>F.z0l0mS^XhzjQ^WpR<v.+Zg2zkxIwMFQ.7hd]D-2`9F&
&w7#U#)?r1W<%#GZgINe3-%(hQct>Acb8C;###################%YJg`l_rJd`WC%S>]dB-Q2(I?W]-ZAJq%/#[nt:bynbNmfr,+%HWA5y*QGyqAb1wo5VSh:S^>BVK&
&14$[xqk61SZ75l#5Eqn>5@C_g03CKl#tL_e7O`wRd8@v#P%i?^*exjIV_j2l=OD<R(V7RoQaRLNB4.y004(cF.7v0EfOh4yfO5>JEt.r+_EnRt69.DkOgD=A^U6o(Qd?r&
&zd]Jkd<Fn_x6UqI0<D0J3hTT)tCZPZC_rrn^9M7n5=iA<[]5Lg@GNQn%:O0A)qMDbk@qUd)Fxp(Gk2P=:a_PK86G;%3.GJKnP,]NIPbL345QoRuarMF,JTRu8JHq(Qm-G&
&;*mRia`A7cXD7#JbkdV$u,>-cr[Qkixaiz<eR7ftU,Z[ApGTh#pU_<rjCp0KydTs*0s7]/3X3]-u`PGfJh###############################################&
&######################################################################################################################%UWpTXz`7:#&
&######$^pYb>Eu#############################################################################################################(Awg@]&
&########################################################################################################(AwhL%###################&
&######(yDHfg>taHVn*dtremsQD/N(GF$Jn6hewx/ea/Yu5n:iS2#-UI]]iS=(gJij##+5ng2AzVUMnUa`-Lr+EnoozrNr8j####################(RFMvj)Hn(vW4&
&_Opo^Jye7wK`cZ%>esz`<dY,=@Xap?0[12G?KrR]6I=:Fo+tDZ.)G9tuPhQ/Y]n6*-g3Rzsrv5*KJ"

end module fplot_glyphs_data
